title: "Lab of Quantum Fields and Strings"
description: "量子场论与弦论理论室 — Quantum Field Theory and String Theory"
baseurl: ""
url: "https://quantumq1.github.io" # change to your GitHub Pages URL
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# site params
author:
  name: "Qu Cao"
  email: "qucao@westlake.edu.cn"

# mathjax
kramdown:
  math_engine: mathjax

permalink: /:title/
